# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-26 15:36
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('publisher', models.CharField(max_length=40)),
                ('publication_schedule', models.CharField(max_length=40, null=True)),
                ('publication_lag', models.CharField(max_length=40, null=True)),
                ('notes', models.TextField(null=True)),
                ('index_url', models.CharField(max_length=200)),
                ('urls', django.contrib.postgres.fields.hstore.HStoreField(null=True)),
                ('requires_captcha', models.BooleanField(default=False)),
                ('licence', models.CharField(max_length=40, null=True)),
                ('licence_attributions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), null=True, size=None)),
                ('core_data', models.BooleanField(default=False)),
                ('research', models.BooleanField(default=False)),
            ],
        ),
    ]
