# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-07 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_searchbookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchbookmark',
            name='url',
            field=models.CharField(default='foo', max_length=200),
            preserve_default=False,
        ),
    ]
