# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-18 06:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_importlog_populate'),
        ('frontend', '0004_auto_20160708_1056'),
    ]

    operations = [
    ]
