# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-08 07:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_auto_20160818_0751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchbookmark',
            name='denominator',
        ),
        migrations.RemoveField(
            model_name='searchbookmark',
            name='numerator',
        ),
    ]
